pub mod adventcoin;
pub mod apartment;
pub mod boarding;
pub mod circuit;
pub mod expense_report;
pub mod geology;
pub mod houses;
pub mod light_grid;
pub mod naughty_or_nice_strings;
mod parsing;
pub mod passport;
pub mod password;
pub mod presents;
